import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            colors: {
                'on-secondary': '#ffffff',
                'on-surface-variant': '#4e453d',
                'secondary-fixed': '#ffddb6',
                'on-tertiary': '#ffffff',
                'tertiary-fixed': '#e4e4cc',
                'tertiary-fixed-dim': '#c8c8b0',
                'secondary-container': '#feb246',
                'error-container': '#ffdad6',
                'surface-container-high': '#ebe8e0',
                'on-surface': '#1c1c17',
                'on-secondary-fixed-variant': '#643f00',
                'tertiary-container': '#3a3b2a',
                'on-primary': '#ffffff',
                'secondary-fixed-dim': '#ffb95a',
                'on-error': '#ffffff',
                'tertiary': '#242516',
                'on-tertiary-fixed': '#1b1d0e',
                'surface-container-low': '#f6f3eb',
                'error': '#ba1a1a',
                'surface-bright': '#fcf9f1',
                'outline': '#80756c',
                'on-error-container': '#93000a',
                'primary-fixed': '#fedcbe',
                'on-primary-container': '#bd9f83',
                'outline-variant': '#d2c4ba',
                'on-tertiary-container': '#a4a58f',
                'on-background': '#1c1c17',
                'surface-container': '#f1eee6',
                'surface': '#fcf9f1',
                'on-secondary-fixed': '#2a1800',
                'primary-container': '#4b3621',
                'on-secondary-container': '#6f4600',
                'primary': '#33210d',
                'inverse-surface': '#31312b',
                'secondary': '#845400',
                'inverse-on-surface': '#f3f1e9',
                'background': '#fcf9f1',
                'on-primary-fixed': '#291806',
                'surface-container-lowest': '#ffffff',
                'primary-fixed-dim': '#e1c1a4',
                'on-tertiary-fixed-variant': '#474836',
                'surface-dim': '#dcdad2',
                'surface-container-highest': '#e5e2db',
                'on-primary-fixed-variant': '#59422c',
                'surface-variant': '#e5e2db',
                'inverse-primary': '#e1c1a4',
                'surface-tint': '#725a42',
            },
            fontFamily: {
                sans: ['"Mulish"', ...defaultTheme.fontFamily.sans],
                headline: ['"Ovo"', 'serif'],
                body: ['"Mulish"', 'sans-serif'],
                label: ['"Mulish"', 'sans-serif'],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1rem',
                full: '9999px',
            },
        },
    },

    plugins: [forms],
};
